config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.turbo_stream
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        # format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        # format.json { render :show, status: :ok, location: @job }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy!

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      # format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, class: "contents") do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 flex items-center">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 flex items-center">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "border rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>" class= "mt-4" >
  <p class="my-5 flex items-center">
    <strong class="block font-medium mb-1 mr-2">Title:</strong>
    <%= job.title %>
  </p>

  <p class="my-5 flex items-center">
    <strong class="block font-medium mb-1 mr-2">Description:</strong>
    <%= job.description %>
  </p>

  <p>
    <%= link_to "Show", job, class: "border ml-2 rounded-lg p-3 bg-gray-100 inline-block font-medium" %>
  </p>

  <%= button_to "Destroy", job, method: :delete, class: "border mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
</div>

app/views/jobs/create.turbo_stream.erb
<%= turbo_stream.append "jobs", @job %>

app/views/jobs/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@job) %>

app/views/jobs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing job</h1>
  
  <%= turbo_frame_tag "job" do %>
    <%= render "form", job: @job %>
    <%= link_to "Show this job", @job, class: "border ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <% end %>
  <%= link_to "Back to jobs", jobs_path, class: "border ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/jobs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Jobs" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Jobs</h1>
  </div>

  <%= turbo_frame_tag "new_job", src: new_job_path, target: "_top", class:"rounded-lg p-3 text-black inline-block font-medium text-center" %>

  <div id="jobs" class="min-w-full">
    <% @jobs.each do |job| %>
      <%= render job %>
    <% end %>
  </div>

</div>

app/views/jobs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New job</h1>
  <%= turbo_frame_tag "new_job", target: "_top", class:"rounded-lg p-3 text-black inline-block font-medium text-center" do %>
    <%= render "form", job: @job %>
  <% end %>
  <%= link_to "Back to jobs", jobs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/jobs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= turbo_frame_tag "job" do %>
      <p class="my-5 flex items-center">
      <strong class="block font-medium mb-1 mr-2">Title:</strong>
        <%= @job.title %>
      </p>

    <p class="my-5 flex items-center">
      <strong class="block font-medium mb-1 mr-2">Description:</strong>
      <%= @job.description %>
    </p>

      <%= link_to "Edit this job", edit_job_path(@job), class: "border mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
     
    <% end %>
    <%= link_to "Back to jobs", jobs_path, "data-turbo-frame": "_top",
    class: "border ml-2 rounded-lg py-3 px-]5 bg-gray-100 inline-block font-medium" %>

  </div>
</div>

app/views/jobs/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@job), partial: "jobs/job", locals: { job: @job } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
        <%= yield %>
    </main>
  </body>
</html>